name             'opsworks_elasticsearch_cookbook'
maintainer       'eiTanLaVi'
maintainer_email 'lavi.eitan@gmail.com'
description      'ElasticSearch OpsWorks Custom'
long_description 'ElasticSearch OpsWorks Custom'
version          '0.1.0'

provides 'opsworks_elasticsearch_cookbook::esplugins'
provides 'opsworks_elasticsearch_cookbook::esmonit'
provides 'opsworks_elasticsearch_cookbook::cloudwatch-custom' 
provides 'opsworks_elasticsearch_cookbook::allocation-awareness' 
